install:
  - appveyor DownloadFile "https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-32-bit.zip" -FileName "sf.zip"
  - dir
  - 7z x sf.zip C:\Qt\sfml
  - set QTDIR=C:\Qt\5.11\mingw53_32
  - cd C:\Qt\
  - dir
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - qmake djog_unos_2018.pro
  - mingw32-make
